[tool.poetry]
name = "repl_python3_kaeya"
version = "0.1.0"
description = ""
authors = ["Rishiraj0100 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
quart = "^0.16.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
